---
permalink: sm-storage/change-configuration-settings-for-a-volume-group.html 
sidebar: sidebar 
keywords: change, raid level, volume group 
summary: 您可以更改卷组的RAID级别、以满足访问该卷组的应用程序的性能需求。此操作将更改卷组的RAID级别、而不会影响数据I/O 
---
= 更改卷组的RAID级别
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以更改卷组的RAID级别、以满足访问该卷组的应用程序的性能需求。此操作将更改卷组的RAID级别、而不会影响数据I/O

.开始之前
* 卷组必须处于最佳状态。
* 卷组中必须有足够的容量才能转换为新的RAID级别。
* 您不能更改池的RAID级别。System Manager会自动将池配置为RAID 6。


.关于此任务
此操作开始后、您将无法取消。在此操作期间、您的数据将保持可用。

有关RAID级别的更多信息

[cols="2*"]
|===
| RAID级别 | Description 


 a| 
RAID 0条带化
 a| 
提供高性能、但不提供任何数据冗余。如果卷组中的一个驱动器发生故障、则所有关联卷都会发生故障、并且所有数据都将丢失。

条带化RAID组将两个或更多驱动器组合成一个大型逻辑驱动器。



 a| 
RAID 1镜像
 a| 
提供高性能和最佳数据可用性、适用于在企业或个人级别存储敏感数据。

通过自动将一个驱动器的内容镜像到镜像对中的第二个驱动器来保护数据。它可以在单个驱动器发生故障时提供保护。



 a| 
RAID 10条带化/镜像
 a| 
提供RAID 0 (条带化)和RAID 1 (镜像)的组合、并在选择四个或更多驱动器时实现。

RAID 10适用于需要高性能和容错能力的高卷事务应用程序、例如数据库。



 a| 
RAID 5
 a| 
最适合多用户环境(例如数据库或文件系统存储)、其中、典型I/O大小较小且读取活动比例较高。



 a| 
RAID 6
 a| 
最适合需要RAID 5以上冗余保护但不需要高写入性能的环境。

|===
使用命令行界面(CLI)只能将RAID 3分配给卷组。

.步骤
. 选择*菜单：存储(池和卷组)*。
. 选择要编辑的卷组、然后单击*查看/编辑设置*。
+
此时将显示卷组设置对话框。

. 从下拉列表中选择RAID级别、然后单击*保存*。
+
如果因RAID级别更改而导致容量减少、卷冗余丢失或磁盘架/抽屉丢失保护丢失、则会显示一个确认对话框。选择*是*继续；否则单击*否*。



.结果
更改卷组的RAID级别时、System Manager会更改组成卷组的每个卷的RAID级别。在此操作期间、性能可能会受到轻微影响。
