---
permalink: sm-storage/create-synchronous-mirrored-volume.html 
sidebar: sidebar 
keywords: create, synchronous, mirrored, volume 
summary: 您可以同步镜像卷、以便在存储阵列之间实时复制数据、从而保护您的信息、使其不会受到系统和站点故障的影响。为此、您可以选择要在本地存储阵列与远程存储阵列之间的同步镜像关系中使用的主卷和二级卷。 
---
= 创建同步镜像卷
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以同步镜像卷、以便在存储阵列之间实时复制数据、从而保护您的信息、使其不会受到系统和站点故障的影响。为此、您可以选择要在本地存储阵列与远程存储阵列之间的同步镜像关系中使用的主卷和二级卷。

.开始之前
* 由于同步镜像功能需要管理多个存储阵列、因此您必须安装基于浏览器的SANtricity Unified Manager、并发现要在其中镜像数据的两个存储阵列。然后、在Unified Manager中、选择主卷的存储阵列并单击*启动*以打开基于浏览器的SANtricity 系统管理器。
* 您必须有两个存储阵列。
* 每个存储阵列必须具有两个控制器。
* 主卷和二级卷的存储阵列可以运行不同的操作系统版本。支持的最低版本为7.84。
* 您必须知道本地和远程存储阵列的密码。
* 本地和远程存储阵列必须通过光纤通道网络结构进行连接。
* 您必须已创建要在同步镜像关系中使用的主卷和二级卷。


同步镜像卷的过程分为多步操作步骤 ：

*  1: Select the primary volume
*  2: Select the secondary volume
*  3: Select synchronization settings


一个卷只能参与一个镜像关系。



== 第1步：选择主卷

[role="lead"]
您必须选择要在同步镜像关系中使用的主卷。此卷在镜像关系中具有主要角色。

.开始之前
* 您必须已创建要在同步镜像关系中使用的主卷。
* 主卷必须是标准卷。它不能是精简卷或快照卷。


.步骤
. 要访问同步镜像序列、请执行以下操作之一：
+
** 选择菜单：Storage[Synchronous Mirroring> Mirror volume]。
** 选择菜单：Storage[卷>复制服务>同步镜像卷]。此时将显示*创建同步镜像对*对话框。


. 选择要用作镜像中主卷的现有卷。
+
[NOTE]
====
如果在卷磁贴中选择了某个卷、并且该卷符合镜像条件、则默认情况下将选中该卷。

====
. 选择*下一步*并转到  2: Select the secondary volume。




== 第2步：选择二级卷

[role="lead"]
您必须选择要在镜像关系中使用的二级卷。此卷将在镜像关系中拥有二级角色。

.开始之前
* 您必须已创建要在同步镜像关系中使用的二级卷。
* 二级卷必须是标准卷。它不能是精简卷或快照卷。
* 二级卷必须至少与主卷大小相同。


在远程存储阵列上选择二级卷时、系统会显示一个列表、其中列出了该镜像对符合条件的所有卷。不符合使用条件的任何卷不会显示在该列表中。

此对话框中显示的卷按容量排序、从最接近主卷容量的卷开始。容量相同的卷按字母顺序排序。

.步骤
. 选择要与本地存储阵列建立镜像关系的远程存储阵列。
+
[NOTE]
====
如果远程存储阵列受密码保护、则系统会提示输入密码。

====
+
** 存储阵列按其存储阵列名称列出。如果您尚未为存储阵列命名、则该存储阵列将列为"未命名"。
** 如果要使用的存储阵列不在列表中、请使用SANtricity 存储管理器的企业管理窗口(EMW)添加该存储阵列。选择菜单：编辑[添加存储阵列]。


. 选择要用作镜像中二级卷的现有卷。
+
[NOTE]
====
如果选择的二级卷的容量大于主卷、则可用容量将限制为主卷的大小。

====
. 单击*下一步*并转到  3: Select synchronization settings。




== 第3步：选择同步设置

[role="lead"]
您必须设置在通信中断后主卷的控制器所有者与二级卷重新同步数据的优先级。您还必须选择手动或自动重新同步策略。

.步骤
. 使用滑块栏设置同步优先级。
+
同步优先级用于确定在通信中断后、与服务I/O请求相比、用于完成初始同步和重新同步操作的系统资源量。

+
此对话框中设置的优先级会同时对主卷和二级卷进行适用场景。您可以稍后通过选择菜单：Storage[同步镜像>更多>编辑设置]来修改主卷上的速率。

+
.有关同步速率的更多信息
====
同步优先级速率有五种：

** 最低
** 低
** 中等
** 高
** 最高如果将同步优先级设置为最低速率、则会优先处理I/O活动、并且重新同步操作所需时间更长。如果将同步优先级设置为最高比率、则会优先执行重新同步操作、但存储阵列的I/O活动可能会受到影响。


====
. 选择是手动还是自动重新同步远程存储阵列上的镜像对。
+
** *手动*(建议选项)—选择此选项可要求在恢复与镜像对的通信后手动恢复同步。此选项提供了恢复数据的最佳机会。
** *自动*—选择此选项可在与镜像对的通信恢复后自动开始重新同步。要手动恢复同步、请转到菜单：Storage[Synchronous Mirroring]、突出显示表中的镜像对、然后在*更多*下选择*恢复*。


. 单击*完成*以完成同步镜像序列。


System Manager将执行以下操作：

* 激活同步镜像功能。
* 开始在本地存储阵列和远程存储阵列之间进行初始同步。
* 设置同步优先级和重新同步策略。


选择菜单：主页(查看正在执行的操作)以查看同步镜像操作的进度。此操作可能会很长，并且可能会影响系统性能。
