---
settings:
  name: SANtricity 11.5
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: SANtricity 软件
    url: "/e-series-santricity-115"
    version-number: '11.5'
  - name: SANtricity 软件
    url: "/e-series-santricity"
    version-number: '11.7'
  - name: SANtricity 软件
    url: "/e-series-santricity-116"
    version-number: '11.6'
  langs: zh-cn,us-en,ja-jp,zh-tw,ko-kr
sidebar:
  entries:
  - title: SANtricity 11.5文档
    url: "/index.html"
  - section: sm-interface
  - section: sm-storage
  - section: sm-mirroring
  - section: sm-hardware
  - section: sm-settings
  - section: sm-support
  - title: 法律声明
    url: "/legal-notices.html"
