---
permalink: sm-mirroring/considerations-for-setting-up-asynchronous-mirroring.html 
sidebar: sidebar 
keywords: considerations, setting up, asynchronous, mirror 
summary: 为了确保成功配置和设置、在规划过程中请牢记一些关键注意事项。 
---
= 设置异步镜像的注意事项
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
为了确保成功配置和设置、在规划过程中请牢记一些关键注意事项。



== 启动SANtricity 统一管理器

* 主阵列和二级阵列中的每个控制器都必须配置一个以太网管理端口、并且必须连接到您的网络。
* 可以通过打开SANtricity 统一管理器来配置异步镜像。任何镜像关系都要求SANtricity Unified Manager发现本地和远程存储系统并将其列出。
* 您必须已安装基于浏览器的SANtricity Unified Manager、并已发现要在其之间镜像数据的两个存储阵列。然后、在Unified Manager中、选择主卷的存储阵列、然后单击启动以打开基于浏览器的SANtricity 系统管理器。




== 正在激活

在使用异步镜像之前、您必须在参与镜像操作的每个存储阵列上激活此镜像。可以通过CLI、REST API或管理图形用户界面(GUI)来激活。

* 对于由SANtricity System Manager (E2800、E5700、EF570)管理的系统、不需要单独的激活步骤；在设置镜像组/对时、会在后台激活。
* 对于由SANtricity 存储管理器(E2700、E5600、EF560)管理的系统、异步镜像将在未由SANtricity System Manager管理的原有系统上使用图形用户界面激活。如果使用iSCSI进行异步镜像、则不需要执行激活步骤。




== Web服务证书和建议的浏览器

* *可信证书*
+
对于涉及由SANtricity System Manager管理的系统的镜像、建议在SANtricity Unified Manager中导入Web服务的可信证书、以便存储系统能够向Web服务器进行身份验证。SANtricity Unified Manager中的步骤如下：

+
.. 为安装SANtricity Unified Manager的计算机生成证书签名请求(CSR)。
.. 将CSR发送给证书颁发机构(CA)。
.. 当CA发回签名证书时、请在Unified Manager中导入。


* *自签名证书*
+
也可以使用自签名证书。如果管理员尝试在不导入签名证书的情况下配置镜像、则SANtricity 系统管理器将显示一个错误对话框、允许管理员接受自签名证书。在这种情况下、建议使用最新版本的Chrome或Firefox作为浏览器。

+
您可以使用Unified Manager接受自签名证书或安装自己的安全证书、并导航到菜单：Certificate[证书管理]。





== 支持的连接

异步镜像可以使用FC或iSCSI连接、也可以同时使用这两种连接在本地和远程存储系统之间进行通信。在创建镜像一致性组(也称为异步镜像组)时、如果这两个组都连接到远程存储阵列、则管理员可以为该组选择FC或iSCSI。不会从一种通道类型故障转移到另一种通道类型。

异步镜像使用存储阵列的主机端I/O端口将镜像数据从主端传输到二级端。

* *通过光纤通道(FC)接口镜像*
+
存储阵列的每个控制器都将其编号最高的FC主机端口专用于镜像操作。

+
如果控制器同时具有基本FC端口和主机接口卡(HIC) FC端口、则编号最高的端口位于HIC上。登录到专用端口的任何主机都将注销、并且不接受任何主机登录请求。只有参与镜像操作的控制器才会接受此端口上的I/O请求。

+
专用镜像端口必须连接到支持目录服务和名称服务接口的FC网络结构环境。特别是、不支持将FC-AL和点对点作为参与镜像关系的控制器之间的连接选项。

* *通过iSCSI接口镜像*
+
与FC不同、iSCSI不需要专用端口。在iSCSI环境中使用异步镜像时、无需将存储阵列的任何前端iSCSI端口专用于异步镜像；这些端口可用于异步镜像流量和主机到阵列I/O连接。

+
控制器会维护一个远程存储系统列表、iSCSI启动程序会尝试与这些系统建立会话。成功建立iSCSI连接的第一个端口将用于此后与该远程存储阵列进行的所有通信。如果通信失败、则会尝试使用所有可用端口进行新会话。

+
iSCSI端口在阵列级别逐个端口进行配置。用于配置消息传送和数据传输的控制器间通信使用全局设置、包括以下设置：

+
** VLAN：本地系统和远程系统必须具有相同的VLAN设置才能进行通信
** iSCSI侦听端口
** 巨型帧
** 以太网优先级


+
[NOTE]
====
iSCSI控制器间通信必须使用主机连接端口、而不是管理以太网端口。

====


异步镜像使用存储阵列的主机端I/O端口将镜像数据从主端传输到二级端。由于异步镜像适用于延迟较高、成本较低的网络、因此iSCSI (以及基于TCP/IP的连接)非常适合它。在iSCSI环境中使用异步镜像时、无需将阵列的任何前端iSCSI端口专用于异步镜像；这些端口可用于异步镜像流量和主机到阵列I/O连接
