---
permalink: sm-hardware/configure-nvme-over-roce-ports-hardware.html 
sidebar: sidebar 
keywords: configure, nvme, roce, ports 
summary: '如果您的控制器包括通过RoCE连接NVMe (基于融合以太网的RDMA)、则可以从硬件页面或系统页面配置NVMe端口设置。' 
---
= 配置基于RoCE的NVMe端口
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的控制器包括通过RoCE连接NVMe (基于融合以太网的RDMA)、则可以从硬件页面或系统页面配置NVMe端口设置。

.开始之前
* 您的控制器必须包含一个基于RoCE的NVMe主机端口；否则、System Manager中不提供基于RoCE的NVMe设置。
* 您必须知道主机连接的IP地址。


.关于此任务
您可以从硬件页面或菜单：设置[系统]访问基于RoCE的NVMe配置。此任务介绍如何从*硬件*页面配置端口。

[NOTE]
====
只有当存储阵列的控制器包含基于 RoCE 的 NVMe 端口时，才会显示基于 RoCE 的 NVMe 设置和功能。

====
.步骤
. 选择 * 硬件 * 。
. 如果图形显示了驱动器，请单击 * 显示磁盘架背面 * 。
+
此图将发生变化，以显示控制器，而不是驱动器。

. 单击具有要配置的基于 RoCE 的 NVMe 端口的控制器。
+
此时将显示控制器的上下文菜单。

. 选择 * 配置基于 RoCE 的 NVMe 端口 * 。
+
此时将打开*通过RoCE端口配置NVMe对话框*。

. 在下拉列表中、选择要配置的HIC端口。
. 单击 * 下一步 * 。
+
要查看所有端口设置、请单击对话框右侧的显示更多端口设置链接。

+
.字段详细信息
[%collapsible]
====
|===
| 端口设置 | Description 


 a| 
已配置以太网端口速度
 a| 
在端口上选择与SFP速度功能匹配的速度。



 a| 
启用 IPv4/Enable IPv6
 a| 
选择一个或两个选项以启用对 IPv4 和 IPv6 网络的支持。


NOTE: 如果要禁用端口访问、请取消选中这两个复选框。



 a| 
MTU大小(可通过单击显示更多端口设置来查看。)
 a| 
如有必要，请为最大传输单元（ Maximum Transmission Unit ， MTU ）输入一个新大小（以字节为单位）。

默认最大传输单元（ Maximum Transmission Unit ， MTU ）大小为每帧 1500 字节。您必须输入一个介于 1500 和 9000 之间的值。

|===
====
+
如果选择启用IPv4、则在单击下一步后、将打开一个对话框、用于选择IPv4设置。如果选择启用IPv6、则在单击下一步后、将打开一个对话框、用于选择IPv6设置。如果同时选择了这两个选项、则IPv4设置对话框将首先打开、然后单击下一步、IPv6设置对话框将打开。

. 自动或手动配置 IPv4 和 / 或 IPv6 设置。
+
.字段详细信息
[%collapsible]
====
|===
| 端口设置 | Description 


 a| 
自动获取配置
 a| 
选择此选项可自动获取配置。



 a| 
手动指定静态配置
 a| 
选择此选项，然后在字段中输入静态地址。(如果需要、可以剪切地址并将其粘贴到字段中。) 对于IPv4、请包括网络子网掩码和网关。对于 IPv6 ，请包括可路由的 IP 地址和路由器 IP 地址。

|===
====
. 单击 * 完成 * 。

