---
permalink: sm-settings/step-1-complete-a-csr.html 
sidebar: sidebar 
keywords: complete, ca certificate, signing, request, csr, controllers 
summary: '要接收存储阵列控制器的证书颁发机构(Certificate Authority、CA)证书、您必须先为存储阵列中的每个控制器生成证书签名请求(Certificate Signing Request、CSR)文件。' 
---
= 完成控制器的CA证书签名请求(CSR)
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
要接收存储阵列控制器的证书颁发机构(CA)证书、您必须先为存储阵列中的每个控制器生成证书签名请求(CSR)文件。

.开始之前
* 您必须使用包含安全管理员权限的用户配置文件登录。否则、不会显示证书功能。


此任务介绍如何生成要发送给CA以接收控制器的已签名管理证书的.csr文件(证书签名请求)。您必须提供有关您的组织的信息以及控制器的IP地址或DNS名称。在此任务期间、如果存储阵列中只有一个控制器、则会生成一个.csr文件；如果有两个控制器、则会生成两个.csr文件。

.步骤
. 选择菜单：设置[证书]。
. 从*阵列管理*选项卡中、选择*完成CSR*。
+
[NOTE]
====
如果显示一个对话框、提示您接受第二个控制器的自签名证书、请单击*接受自签名证书*以继续。

====
. 输入以下信息、然后单击*下一步*：
+
** *组织*—贵公司或组织的法定全名。包括后缀、例如Inc.或Corp.
** *组织单位(可选)*—组织中负责处理证书的部门。
** *城市/位置*—存储阵列或业务所在的城市。
** *省/自治区/直辖市(可选)*—存储阵列或业务所在的省/自治区/直辖市。
** *国家/地区ISO代码*—您所在国家/地区的两位数ISO (国际标准化组织)代码、例如美国。


+
[CAUTION]
====
某些字段可能会预先填充相应的信息、例如控制器的IP地址。请勿更改预先填充的值、除非您确定这些值不正确。例如、如果尚未完成CSR、则控制器IP地址将设置为"`localhost.`"。 在这种情况下、您必须将"`localhost`"更改为控制器的DNS名称或IP地址。

====
. 验证或输入有关存储阵列中控制器A的以下信息：
+
** *控制器A公用名*-默认情况下、显示控制器A的IP地址或DNS名称。请确保此地址正确无误；它必须与您在浏览器中输入的内容完全匹配、才能访问System Manager。
** *控制器A备用IP地址*-如果公用名称为IP地址、则可以选择为控制器A输入任何其他IP地址或别名对于多个条目、请使用逗号分隔格式。
** *控制器A备用DNS名称*-如果公用名是DNS名称、请为控制器A输入任何其他DNS名称对于多个条目、请使用逗号分隔格式。如果没有备用DNS名称、但您在第一个字段中输入了DNS名称、请将此名称复制到此处。如果存储阵列只有一个控制器、则可以使用*完成*按钮。如果存储阵列有两个控制器、则可以使用*下一步*按钮。


+
[NOTE]
====
首次创建CSR请求时、请勿单击*跳过此步骤*链接。在错误恢复情况下提供此链接。在极少数情况下、一个控制器上的CSR请求可能会失败、而另一个控制器上的CSR请求则可能不会失败。通过此链接、您可以跳过在已定义的控制器A上创建CSR请求的步骤、并继续执行在控制器B上重新创建CSR请求的下一步

====
. 如果只有一个控制器、请单击*完成*。如果有两个控制器、请单击*下一步*以输入控制器B的信息(与上述相同)、然后单击*完成*。
+
对于单个控制器、会将一个.csr文件下载到本地系统。对于双控制器、将下载两个.csr文件。下载内容的文件夹位置取决于您的浏览器。

. 将.csr文件发送到CA。


收到数字证书后、请导入CA发送给您的相应证书文件。
